### ISSUE TITLE
Support Node > 4.0

### ISSUE THREAD

**Issue by nickdaugherty** [Simperium/node-simperium#10]
The current EventEmitter usage is incompatible with Node > 4.0:

```
events.js:24
  this.domain = null;
              ^
TypeError: Cannot set property 'domain' of undefined
    at EventEmitter.init (events.js:24:15)
    at EventEmitter (events.js:6:21)
    at new Heartbeat (/home/travis/build/Automattic/vipv2-api/node_modules/simperium/lib/simperium/client.js:180:3)
    at new Client (/home/travis/build/Automattic/vipv2-api/node_modules/simperium/lib/simperium/client.js:27:20)
...
```

[Line 180 of client.js](https://github.com/Simperium/node-simperium/blob/664121205abbe37c8d05a9528e9f23bef6ffa48e/lib/simperium/client.js#L180):

```
EventEmitter(this);
```

Replacing all instances with `EventEmitter.call(this);` appears to fix the issue.

**Comment by joshbetz** [comment]
Related: https://github.com/Simperium/node-simperium/pull/9
